#!/bin/sh

# 1. Query database of installed packages
NO_INSTALLED=$(ls $PACKAGEDB 2>&1 >/dev/null | grep "ls" | wc -l)

# 2. Print the result of the query
if [ $NO_INSTALLED = 1 ]
then
	echo "No packages are installed yet!"
else
	ls $PACKAGEDB | cut -f 1 -d '.'
fi
